# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.disksize.size = '40GB'

  config.vm.define :distromagma, autostart: false do |distromagma|
    distromagma.vm.hostname = "distro-magma"
    distromagma.vm.network "private_network", ip: "192.168.62.176", nic_type: "82540EM"
    distromagma.vm.network "private_network", ip: "192.168.130.74", nic_type: "82540EM"

    distromagma.vm.provider "virtualbox" do |vb|
      vb.name = "distro-magma"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "16384"]
      vb.customize ["modifyvm", :id, "--cpus", "8"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end
end
