load("//:my_custom_rule.bzl", "write_new_file")

write_new_file(
    name = "write_my_custom_message_into_file",
    my_input_file = "//:my_input_file.txt",
    out_file_name = "my_output_awsome"
    )